<?php

namespace Database\Seeders;

use App\Models\MasterDistrict;
use Illuminate\Database\Seeder;

class MasterDistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $districts = [
            ['name' => 'Anantnag', 'state_id' => 15],
            ['name' => 'Bandipore', 'state_id' => 15],
            ['name' => 'Baramulla', 'state_id' => 15],
            ['name' => 'Budgam', 'state_id' => 15],
            ['name' => 'Doda', 'state_id' => 15],
            ['name' => 'Ganderbal', 'state_id' => 15],
            ['name' => 'Jammu', 'state_id' => 15],
            ['name' => 'Kargil', 'state_id' => 15],
            ['name' => 'Kathua', 'state_id' => 15],
            ['name' => 'Kishtwar', 'state_id' => 15],
            ['name' => 'Kulgam', 'state_id' => 15],
            ['name' => 'Kupwara', 'state_id' => 15],
            ['name' => 'Leh (Ladakh)', 'state_id' => 15],
            ['name' => 'Poonch', 'state_id' => 15],
            ['name' => 'Pulwama', 'state_id' => 15],
            ['name' => 'Rajouri', 'state_id' => 15],
            ['name' => 'Ramban', 'state_id' => 15],
            ['name' => 'Reasi', 'state_id' => 15],
            ['name' => 'Samba', 'state_id' => 15],
            ['name' => 'Shopian', 'state_id' => 15],
            ['name' => 'Srinagar', 'state_id' => 15],
            ['name' => 'Udhampur', 'state_id' => 15],
            ['name' => 'Bilaspur (Himachal Pradesh)', 'state_id' => 14],
            ['name' => 'Chamba', 'state_id' => 14],
            ['name' => 'Hamirpur (Himachal Pradesh)', 'state_id' => 14],
            ['name' => 'Kangra', 'state_id' => 14],
            ['name' => 'Kinnaur', 'state_id' => 14],
            ['name' => 'Kullu', 'state_id' => 14],
            ['name' => 'Lahul & Spiti', 'state_id' => 14],
            ['name' => 'Mandi', 'state_id' => 14],
            ['name' => 'Shimla', 'state_id' => 14],
            ['name' => 'Sirmaur', 'state_id' => 14],
            ['name' => 'Solan', 'state_id' => 14],
            ['name' => 'Una', 'state_id' => 14],
            ['name' => 'Amritsar', 'state_id' => 28],
            ['name' => 'Barnala', 'state_id' => 28],
            ['name' => 'Bathinda', 'state_id' => 28],
            ['name' => 'Faridkot', 'state_id' => 28],
            ['name' => 'Fatehgarh Sahib', 'state_id' => 28],
            ['name' => 'Firozpur', 'state_id' => 28],
            ['name' => 'Gurdaspur', 'state_id' => 28],
            ['name' => 'Hoshiarpur', 'state_id' => 28],
            ['name' => 'Jalandhar', 'state_id' => 28],
            ['name' => 'Kapurthala', 'state_id' => 28],
            ['name' => 'Ludhiana', 'state_id' => 28],
            ['name' => 'Mansa', 'state_id' => 28],
            ['name' => 'Moga', 'state_id' => 28],
            ['name' => 'Muktsar', 'state_id' => 28],
            ['name' => 'Patiala', 'state_id' => 28],
            ['name' => 'Rupnagar (Ropar)', 'state_id' => 28],
            ['name' => 'Sahibzada Ajit Singh Nagar (Mohali)', 'state_id' => 28],
            ['name' => 'Sangrur', 'state_id' => 28],
            ['name' => 'Shahid Bhagat Singh Nagar (Nawanshahr)', 'state_id' => 28],
            ['name' => 'Tarn Taran', 'state_id' => 28],
            ['name' => 'Chandigarh', 'state_id' => 6],
            ['name' => 'Almora', 'state_id' => 34],
            ['name' => 'Bageshwar', 'state_id' => 34],
            ['name' => 'Chamoli', 'state_id' => 34],
            ['name' => 'Champawat', 'state_id' => 34],
            ['name' => 'Dehradun', 'state_id' => 34],
            ['name' => 'Haridwar', 'state_id' => 34],
            ['name' => 'Nainital', 'state_id' => 34],
            ['name' => 'Pauri Garhwal', 'state_id' => 34],
            ['name' => 'Pithoragarh', 'state_id' => 34],
            ['name' => 'Rudraprayag', 'state_id' => 34],
            ['name' => 'Tehri Garhwal', 'state_id' => 34],
            ['name' => 'Udham Singh Nagar', 'state_id' => 34],
            ['name' => 'Uttarkashi', 'state_id' => 34],
            ['name' => 'Ambala', 'state_id' => 13],
            ['name' => 'Bhiwani', 'state_id' => 13],
            ['name' => 'Faridabad', 'state_id' => 13],
            ['name' => 'Fatehabad', 'state_id' => 13],
            ['name' => 'Gurgaon', 'state_id' => 13],
            ['name' => 'Hisar', 'state_id' => 13],
            ['name' => 'Jhajjar', 'state_id' => 13],
            ['name' => 'Jind', 'state_id' => 13],
            ['name' => 'Kaithal', 'state_id' => 13],
            ['name' => 'Karnal', 'state_id' => 13],
            ['name' => 'Kurukshetra', 'state_id' => 13],
            ['name' => 'Mahendragarh', 'state_id' => 13],
            ['name' => 'Mewat', 'state_id' => 13],
            ['name' => 'Palwal', 'state_id' => 13],
            ['name' => 'Panchkula', 'state_id' => 13],
            ['name' => 'Panipat', 'state_id' => 13],
            ['name' => 'Rewari', 'state_id' => 13],
            ['name' => 'Rohtak', 'state_id' => 13],
            ['name' => 'Sirsa', 'state_id' => 13],
            ['name' => 'Sonipat', 'state_id' => 13],
            ['name' => 'Yamuna Nagar', 'state_id' => 13],
            ['name' => 'Central Delhi', 'state_id' => 10],
            ['name' => 'East Delhi', 'state_id' => 10],
            ['name' => 'New Delhi', 'state_id' => 10],
            ['name' => 'North Delhi', 'state_id' => 10],
            ['name' => 'North East Delhi', 'state_id' => 10],
            ['name' => 'North West Delhi', 'state_id' => 10],
            ['name' => 'South Delhi', 'state_id' => 10],
            ['name' => 'South West Delhi', 'state_id' => 10],
            ['name' => 'West Delhi', 'state_id' => 10],
            ['name' => 'Ajmer', 'state_id' => 29],
            ['name' => 'Alwar', 'state_id' => 29],
            ['name' => 'Banswara', 'state_id' => 29],
            ['name' => 'Baran', 'state_id' => 29],
            ['name' => 'Barmer', 'state_id' => 29],
            ['name' => 'Bharatpur', 'state_id' => 29],
            ['name' => 'Bhilwara', 'state_id' => 29],
            ['name' => 'Bikaner', 'state_id' => 29],
            ['name' => 'Bundi', 'state_id' => 29],
            ['name' => 'Chittorgarh', 'state_id' => 29],
            ['name' => 'Churu', 'state_id' => 29],
            ['name' => 'Dausa', 'state_id' => 29],
            ['name' => 'Dholpur', 'state_id' => 29],
            ['name' => 'Dungarpur', 'state_id' => 29],
            ['name' => 'Ganganagar', 'state_id' => 29],
            ['name' => 'Hanumangarh', 'state_id' => 29],
            ['name' => 'Jaipur', 'state_id' => 29],
            ['name' => 'Jaisalmer', 'state_id' => 29],
            ['name' => 'Jalor', 'state_id' => 29],
            ['name' => 'Jhalawar', 'state_id' => 29],
            ['name' => 'Jhunjhunu', 'state_id' => 29],
            ['name' => 'Jodhpur', 'state_id' => 29],
            ['name' => 'Karauli', 'state_id' => 29],
            ['name' => 'Kota', 'state_id' => 29],
            ['name' => 'Nagaur', 'state_id' => 29],
            ['name' => 'Pali', 'state_id' => 29],
            ['name' => 'Pratapgarh (Rajasthan)', 'state_id' => 29],
            ['name' => 'Rajsamand', 'state_id' => 29],
            ['name' => 'Sawai Madhopur', 'state_id' => 29],
            ['name' => 'Sikar', 'state_id' => 29],
            ['name' => 'Sirohi', 'state_id' => 29],
            ['name' => 'Tonk', 'state_id' => 29],
            ['name' => 'Udaipur', 'state_id' => 29],
            ['name' => 'Agra', 'state_id' => 33],
            ['name' => 'Aligarh', 'state_id' => 33],
            ['name' => 'Allahabad', 'state_id' => 33],
            ['name' => 'Ambedkar Nagar', 'state_id' => 33],
            ['name' => 'Auraiya', 'state_id' => 33],
            ['name' => 'Azamgarh', 'state_id' => 33],
            ['name' => 'Bagpat', 'state_id' => 33],
            ['name' => 'Bahraich', 'state_id' => 33],
            ['name' => 'Ballia', 'state_id' => 33],
            ['name' => 'Balrampur', 'state_id' => 33],
            ['name' => 'Banda', 'state_id' => 33],
            ['name' => 'Barabanki', 'state_id' => 33],
            ['name' => 'Bareilly', 'state_id' => 33],
            ['name' => 'Basti', 'state_id' => 33],
            ['name' => 'Bijnor', 'state_id' => 33],
            ['name' => 'Budaun', 'state_id' => 33],
            ['name' => 'Bulandshahr', 'state_id' => 33],
            ['name' => 'Chandauli', 'state_id' => 33],
            ['name' => 'Chitrakoot', 'state_id' => 33],
            ['name' => 'Deoria', 'state_id' => 33],
            ['name' => 'Etah', 'state_id' => 33],
            ['name' => 'Etawah', 'state_id' => 33],
            ['name' => 'Faizabad', 'state_id' => 33],
            ['name' => 'Farrukhabad', 'state_id' => 33],
            ['name' => 'Fatehpur', 'state_id' => 33],
            ['name' => 'Firozabad', 'state_id' => 33],
            ['name' => 'Gautam Buddha Nagar', 'state_id' => 33],
            ['name' => 'Ghaziabad', 'state_id' => 33],
            ['name' => 'Ghazipur', 'state_id' => 33],
            ['name' => 'Gonda', 'state_id' => 33],
            ['name' => 'Gorakhpur', 'state_id' => 33],
            ['name' => 'Hamirpur', 'state_id' => 33],
            ['name' => 'Hardoi', 'state_id' => 33],
            ['name' => 'Hathras', 'state_id' => 33],
            ['name' => 'Jalaun', 'state_id' => 33],
            ['name' => 'Jaunpur', 'state_id' => 33],
            ['name' => 'Jhansi', 'state_id' => 33],
            ['name' => 'Jyotiba Phule Nagar', 'state_id' => 33],
            ['name' => 'Kannauj', 'state_id' => 33],
            ['name' => 'Kanpur Dehat', 'state_id' => 33],
            ['name' => 'Kanpur Nagar', 'state_id' => 33],
            ['name' => 'Kanshiram Nagar', 'state_id' => 33],
            ['name' => 'Kaushambi', 'state_id' => 33],
            ['name' => 'Kheri', 'state_id' => 33],
            ['name' => 'Kushinagar', 'state_id' => 33],
            ['name' => 'Lalitpur', 'state_id' => 33],
            ['name' => 'Lucknow', 'state_id' => 33],
            ['name' => 'Maharajganj', 'state_id' => 33],
            ['name' => 'Mahoba', 'state_id' => 33],
            ['name' => 'Mainpuri', 'state_id' => 33],
            ['name' => 'Mathura', 'state_id' => 33],
            ['name' => 'Mau', 'state_id' => 33],
            ['name' => 'Meerut', 'state_id' => 33],
            ['name' => 'Mirzapur', 'state_id' => 33],
            ['name' => 'Moradabad', 'state_id' => 33],
            ['name' => 'Muzaffarnagar', 'state_id' => 33],
            ['name' => 'Pilibhit', 'state_id' => 33],
            ['name' => 'Pratapgarh', 'state_id' => 33],
            ['name' => 'Rae Bareli', 'state_id' => 33],
            ['name' => 'Rampur', 'state_id' => 33],
            ['name' => 'Saharanpur', 'state_id' => 33],
            ['name' => 'Sant Kabir Nagar', 'state_id' => 33],
            ['name' => 'Sant Ravidas Nagar (Bhadohi)', 'state_id' => 33],
            ['name' => 'Shahjahanpur', 'state_id' => 33],
            ['name' => 'Shrawasti', 'state_id' => 33],
            ['name' => 'Siddharthnagar', 'state_id' => 33],
            ['name' => 'Sitapur', 'state_id' => 33],
            ['name' => 'Sonbhadra', 'state_id' => 33],
            ['name' => 'Sultanpur', 'state_id' => 33],
            ['name' => 'Unnao', 'state_id' => 33],
            ['name' => 'Varanasi', 'state_id' => 33],
            ['name' => 'Araria', 'state_id' => 5],
            ['name' => 'Arwal', 'state_id' => 5],
            ['name' => 'Aurangabad (Bihar)', 'state_id' => 5],
            ['name' => 'Banka', 'state_id' => 5],
            ['name' => 'Begusarai', 'state_id' => 5],
            ['name' => 'Bhagalpur', 'state_id' => 5],
            ['name' => 'Bhojpur', 'state_id' => 5],
            ['name' => 'Buxar', 'state_id' => 5],
            ['name' => 'Darbhanga', 'state_id' => 5],
            ['name' => 'East Champaran', 'state_id' => 5],
            ['name' => 'Gaya', 'state_id' => 5],
            ['name' => 'Gopalganj', 'state_id' => 5],
            ['name' => 'Jamui', 'state_id' => 5],
            ['name' => 'Jehanabad', 'state_id' => 5],
            ['name' => 'Kaimur (Bhabua)', 'state_id' => 5],
            ['name' => 'Katihar', 'state_id' => 5],
            ['name' => 'Khagaria', 'state_id' => 5],
            ['name' => 'Kishanganj', 'state_id' => 5],
            ['name' => 'Lakhisarai', 'state_id' => 5],
            ['name' => 'Madhepura', 'state_id' => 5],
            ['name' => 'Madhubani', 'state_id' => 5],
            ['name' => 'Munger', 'state_id' => 5],
            ['name' => 'Muzaffarpur', 'state_id' => 5],
            ['name' => 'Nalanda', 'state_id' => 5],
            ['name' => 'Nawada', 'state_id' => 5],
            ['name' => 'Patna', 'state_id' => 5],
            ['name' => 'Purnia', 'state_id' => 5],
            ['name' => 'Rohtas', 'state_id' => 5],
            ['name' => 'Saharsa', 'state_id' => 5],
            ['name' => 'Samastipur', 'state_id' => 5],
            ['name' => 'Saran', 'state_id' => 5],
            ['name' => 'Sheikhpura', 'state_id' => 5],
            ['name' => 'Sheohar', 'state_id' => 5],
            ['name' => 'Sitamarhi', 'state_id' => 5],
            ['name' => 'Siwan', 'state_id' => 5],
            ['name' => 'Supaul', 'state_id' => 5],
            ['name' => 'Vaishali', 'state_id' => 5],
            ['name' => 'West Champaran', 'state_id' => 5],
            ['name' => 'East Sikkim', 'state_id' => 30],
            ['name' => 'North Sikkim', 'state_id' => 30],
            ['name' => 'South Sikkim', 'state_id' => 30],
            ['name' => 'West Sikkim', 'state_id' => 30],
            ['name' => 'Anjaw', 'state_id' => 3],
            ['name' => 'Changlang', 'state_id' => 3],
            ['name' => 'Dibang Valley', 'state_id' => 3],
            ['name' => 'East Kameng', 'state_id' => 3],
            ['name' => 'East Siang', 'state_id' => 3],
            ['name' => 'Kurung Kumey', 'state_id' => 3],
            ['name' => 'Lohit', 'state_id' => 3],
            ['name' => 'Lower Dibang Valley', 'state_id' => 3],
            ['name' => 'Lower Subansiri', 'state_id' => 3],
            ['name' => 'Papum Pare', 'state_id' => 3],
            ['name' => 'Tawang', 'state_id' => 3],
            ['name' => 'Tirap', 'state_id' => 3],
            ['name' => 'Upper Siang', 'state_id' => 3],
            ['name' => 'Upper Subansiri', 'state_id' => 3],
            ['name' => 'West Kameng', 'state_id' => 3],
            ['name' => 'West Siang', 'state_id' => 3],
            ['name' => 'Dimapur', 'state_id' => 25],
            ['name' => 'Kiphire', 'state_id' => 25],
            ['name' => 'Kohima', 'state_id' => 25],
            ['name' => 'Longleng', 'state_id' => 25],
            ['name' => 'Mokokchung', 'state_id' => 25],
            ['name' => 'Mon', 'state_id' => 25],
            ['name' => 'Peren', 'state_id' => 25],
            ['name' => 'Phek', 'state_id' => 25],
            ['name' => 'Tuensang', 'state_id' => 25],
            ['name' => 'Wokha', 'state_id' => 25],
            ['name' => 'Zunheboto', 'state_id' => 25],
            ['name' => 'Bishnupur', 'state_id' => 22],
            ['name' => 'Chandel', 'state_id' => 22],
            ['name' => 'Churachandpur', 'state_id' => 22],
            ['name' => 'Imphal East', 'state_id' => 22],
            ['name' => 'Imphal West', 'state_id' => 22],
            ['name' => 'Senapati', 'state_id' => 22],
            ['name' => 'Tamenglong', 'state_id' => 22],
            ['name' => 'Thoubal', 'state_id' => 22],
            ['name' => 'Ukhrul', 'state_id' => 22],
            ['name' => 'Aizawl', 'state_id' => 24],
            ['name' => 'Champhai', 'state_id' => 24],
            ['name' => 'Kolasib', 'state_id' => 24],
            ['name' => 'Lawngtlai', 'state_id' => 24],
            ['name' => 'Lunglei', 'state_id' => 24],
            ['name' => 'Mamit', 'state_id' => 24],
            ['name' => 'Saiha', 'state_id' => 24],
            ['name' => 'Serchhip', 'state_id' => 24],
            ['name' => 'Dhalai', 'state_id' => 32],
            ['name' => 'North Tripura', 'state_id' => 32],
            ['name' => 'South Tripura', 'state_id' => 32],
            ['name' => 'West Tripura', 'state_id' => 32],
            ['name' => 'East Garo Hills', 'state_id' => 23],
            ['name' => 'East Khasi Hills', 'state_id' => 23],
            ['name' => 'Jaintia Hills', 'state_id' => 23],
            ['name' => 'Ri Bhoi', 'state_id' => 23],
            ['name' => 'South Garo Hills', 'state_id' => 23],
            ['name' => 'West Garo Hills', 'state_id' => 23],
            ['name' => 'West Khasi Hills', 'state_id' => 23],
            ['name' => 'Baksa', 'state_id' => 4],
            ['name' => 'Barpeta', 'state_id' => 4],
            ['name' => 'Bongaigaon', 'state_id' => 4],
            ['name' => 'Cachar', 'state_id' => 4],
            ['name' => 'Chirang', 'state_id' => 4],
            ['name' => 'Darrang', 'state_id' => 4],
            ['name' => 'Dhemaji', 'state_id' => 4],
            ['name' => 'Dhubri', 'state_id' => 4],
            ['name' => 'Dibrugarh', 'state_id' => 4],
            ['name' => 'Dima Hasao (North Cachar Hills)', 'state_id' => 4],
            ['name' => 'Goalpara', 'state_id' => 4],
            ['name' => 'Golaghat', 'state_id' => 4],
            ['name' => 'Hailakandi', 'state_id' => 4],
            ['name' => 'Jorhat', 'state_id' => 4],
            ['name' => 'Kamrup', 'state_id' => 4],
            ['name' => 'Kamrup Metropolitan', 'state_id' => 4],
            ['name' => 'Karbi Anglong', 'state_id' => 4],
            ['name' => 'Karimganj', 'state_id' => 4],
            ['name' => 'Kokrajhar', 'state_id' => 4],
            ['name' => 'Lakhimpur', 'state_id' => 4],
            ['name' => 'Morigaon', 'state_id' => 4],
            ['name' => 'Nagaon', 'state_id' => 4],
            ['name' => 'Nalbari', 'state_id' => 4],
            ['name' => 'Sivasagar', 'state_id' => 4],
            ['name' => 'Sonitpur', 'state_id' => 4],
            ['name' => 'Tinsukia', 'state_id' => 4],
            ['name' => 'Udalguri', 'state_id' => 4],
            ['name' => 'Bankura', 'state_id' => 35],
            ['name' => 'Bardhaman', 'state_id' => 35],
            ['name' => 'Birbhum', 'state_id' => 35],
            ['name' => 'Cooch Behar', 'state_id' => 35],
            ['name' => 'Dakshin Dinajpur (South Dinajpur)', 'state_id' => 35],
            ['name' => 'Darjiling', 'state_id' => 35],
            ['name' => 'Hooghly', 'state_id' => 35],
            ['name' => 'Howrah', 'state_id' => 35],
            ['name' => 'Jalpaiguri', 'state_id' => 35],
            ['name' => 'Kolkata', 'state_id' => 35],
            ['name' => 'Maldah', 'state_id' => 35],
            ['name' => 'Murshidabad', 'state_id' => 35],
            ['name' => 'Nadia', 'state_id' => 35],
            ['name' => 'North 24 Parganas', 'state_id' => 35],
            ['name' => 'Paschim Medinipur (West Midnapore)', 'state_id' => 35],
            ['name' => 'Purba Medinipur (East Midnapore)', 'state_id' => 35],
            ['name' => 'Puruliya', 'state_id' => 35],
            ['name' => 'South 24 Parganas', 'state_id' => 35],
            ['name' => 'Uttar Dinajpur (North Dinajpur)', 'state_id' => 35],
            ['name' => 'Bokaro', 'state_id' => 16],
            ['name' => 'Chatra', 'state_id' => 16],
            ['name' => 'Deoghar', 'state_id' => 16],
            ['name' => 'Dhanbad', 'state_id' => 16],
            ['name' => 'Dumka', 'state_id' => 16],
            ['name' => 'East Singhbhum', 'state_id' => 16],
            ['name' => 'Garhwa', 'state_id' => 16],
            ['name' => 'Giridih', 'state_id' => 16],
            ['name' => 'Godda', 'state_id' => 16],
            ['name' => 'Gumla', 'state_id' => 16],
            ['name' => 'Hazaribagh', 'state_id' => 16],
            ['name' => 'Jamtara', 'state_id' => 16],
            ['name' => 'Khunti', 'state_id' => 16],
            ['name' => 'Koderma', 'state_id' => 16],
            ['name' => 'Latehar', 'state_id' => 16],
            ['name' => 'Lohardaga', 'state_id' => 16],
            ['name' => 'Pakur', 'state_id' => 16],
            ['name' => 'Palamu', 'state_id' => 16],
            ['name' => 'Ramgarh', 'state_id' => 16],
            ['name' => 'Ranchi', 'state_id' => 16],
            ['name' => 'Sahibganj', 'state_id' => 16],
            ['name' => 'Seraikela-Kharsawan', 'state_id' => 16],
            ['name' => 'Simdega', 'state_id' => 16],
            ['name' => 'West Singhbhum', 'state_id' => 16],
            ['name' => 'Angul', 'state_id' => 26],
            ['name' => 'Balangir', 'state_id' => 26],
            ['name' => 'Baleswar', 'state_id' => 26],
            ['name' => 'Bargarh', 'state_id' => 26],
            ['name' => 'Bhadrak', 'state_id' => 26],
            ['name' => 'Boudh', 'state_id' => 26],
            ['name' => 'Cuttack', 'state_id' => 26],
            ['name' => 'Debagarh', 'state_id' => 26],
            ['name' => 'Dhenkanal', 'state_id' => 26],
            ['name' => 'Gajapati', 'state_id' => 26],
            ['name' => 'Ganjam', 'state_id' => 26],
            ['name' => 'Jagatsinghapur', 'state_id' => 26],
            ['name' => 'Jajapur', 'state_id' => 26],
            ['name' => 'Jharsuguda', 'state_id' => 26],
            ['name' => 'Kalahandi', 'state_id' => 26],
            ['name' => 'Kandhamal', 'state_id' => 26],
            ['name' => 'Kendrapara', 'state_id' => 26],
            ['name' => 'Kendujhar', 'state_id' => 26],
            ['name' => 'Khordha', 'state_id' => 26],
            ['name' => 'Koraput', 'state_id' => 26],
            ['name' => 'Malkangiri', 'state_id' => 26],
            ['name' => 'Mayurbhanj', 'state_id' => 26],
            ['name' => 'Nabarangapur', 'state_id' => 26],
            ['name' => 'Nayagarh', 'state_id' => 26],
            ['name' => 'Nuapada', 'state_id' => 26],
            ['name' => 'Puri', 'state_id' => 26],
            ['name' => 'Rayagada', 'state_id' => 26],
            ['name' => 'Sambalpur', 'state_id' => 26],
            ['name' => 'Subarnapur (Sonapur)', 'state_id' => 26],
            ['name' => 'Sundergarh', 'state_id' => 26],
            ['name' => 'Bastar', 'state_id' => 7],
            ['name' => 'Bijapur (Chhattisgarh)', 'state_id' => 7],
            ['name' => 'Bilaspur (Chhattisgarh)', 'state_id' => 7],
            ['name' => 'Dakshin Bastar Dantewada', 'state_id' => 7],
            ['name' => 'Dhamtari', 'state_id' => 7],
            ['name' => 'Durg', 'state_id' => 7],
            ['name' => 'Janjgir-Champa', 'state_id' => 7],
            ['name' => 'Jashpur', 'state_id' => 7],
            ['name' => 'Kabirdham (Kawardha)', 'state_id' => 7],
            ['name' => 'Korba', 'state_id' => 7],
            ['name' => 'Koriya', 'state_id' => 7],
            ['name' => 'Mahasamund', 'state_id' => 7],
            ['name' => 'Narayanpur', 'state_id' => 7],
            ['name' => 'Raigarh (Chhattisgarh)', 'state_id' => 7],
            ['name' => 'Raipur', 'state_id' => 7],
            ['name' => 'Rajnandgaon', 'state_id' => 7],
            ['name' => 'Surguja', 'state_id' => 7],
            ['name' => 'Uttar Bastar Kanker', 'state_id' => 7],
            ['name' => 'Alirajpur', 'state_id' => 20],
            ['name' => 'Anuppur', 'state_id' => 20],
            ['name' => 'Ashok Nagar', 'state_id' => 20],
            ['name' => 'Balaghat', 'state_id' => 20],
            ['name' => 'Barwani', 'state_id' => 20],
            ['name' => 'Betul', 'state_id' => 20],
            ['name' => 'Bhind', 'state_id' => 20],
            ['name' => 'Bhopal', 'state_id' => 20],
            ['name' => 'Burhanpur', 'state_id' => 20],
            ['name' => 'Chhatarpur', 'state_id' => 20],
            ['name' => 'Chhindwara', 'state_id' => 20],
            ['name' => 'Damoh', 'state_id' => 20],
            ['name' => 'Datia', 'state_id' => 20],
            ['name' => 'Dewas', 'state_id' => 20],
            ['name' => 'Dhar', 'state_id' => 20],
            ['name' => 'Dindori', 'state_id' => 20],
            ['name' => 'Guna', 'state_id' => 20],
            ['name' => 'Gwalior', 'state_id' => 20],
            ['name' => 'Harda', 'state_id' => 20],
            ['name' => 'Hoshangabad', 'state_id' => 20],
            ['name' => 'Indore', 'state_id' => 20],
            ['name' => 'Jabalpur', 'state_id' => 20],
            ['name' => 'Jhabua', 'state_id' => 20],
            ['name' => 'Katni', 'state_id' => 20],
            ['name' => 'Khandwa (East Nimar)', 'state_id' => 20],
            ['name' => 'Khargone (West Nimar)', 'state_id' => 20],
            ['name' => 'Mandla', 'state_id' => 20],
            ['name' => 'Mandsaur', 'state_id' => 20],
            ['name' => 'Morena', 'state_id' => 20],
            ['name' => 'Narsinghpur', 'state_id' => 20],
            ['name' => 'Neemuch', 'state_id' => 20],
            ['name' => 'Panna', 'state_id' => 20],
            ['name' => 'Raisen', 'state_id' => 20],
            ['name' => 'Rajgarh', 'state_id' => 20],
            ['name' => 'Ratlam', 'state_id' => 20],
            ['name' => 'Rewa', 'state_id' => 20],
            ['name' => 'Sagar', 'state_id' => 20],
            ['name' => 'Satna', 'state_id' => 20],
            ['name' => 'Sehore', 'state_id' => 20],
            ['name' => 'Seoni', 'state_id' => 20],
            ['name' => 'Shahdol', 'state_id' => 20],
            ['name' => 'Shajapur', 'state_id' => 20],
            ['name' => 'Sheopur', 'state_id' => 20],
            ['name' => 'Shivpuri', 'state_id' => 20],
            ['name' => 'Sidhi', 'state_id' => 20],
            ['name' => 'Singrauli', 'state_id' => 20],
            ['name' => 'Tikamgarh', 'state_id' => 20],
            ['name' => 'Ujjain', 'state_id' => 20],
            ['name' => 'Umaria', 'state_id' => 20],
            ['name' => 'Vidisha', 'state_id' => 20],
            ['name' => 'Ahmedabad', 'state_id' => 12],
            ['name' => 'Amreli', 'state_id' => 12],
            ['name' => 'Anand', 'state_id' => 12],
            ['name' => 'Banaskantha', 'state_id' => 12],
            ['name' => 'Bharuch', 'state_id' => 12],
            ['name' => 'Bhavnagar', 'state_id' => 12],
            ['name' => 'Dahod', 'state_id' => 12],
            ['name' => 'Gandhi Nagar', 'state_id' => 12],
            ['name' => 'Jamnagar', 'state_id' => 12],
            ['name' => 'Junagadh', 'state_id' => 12],
            ['name' => 'Kachchh', 'state_id' => 12],
            ['name' => 'Kheda', 'state_id' => 12],
            ['name' => 'Mahesana', 'state_id' => 12],
            ['name' => 'Narmada', 'state_id' => 12],
            ['name' => 'Navsari', 'state_id' => 12],
            ['name' => 'Panch Mahals', 'state_id' => 12],
            ['name' => 'Patan', 'state_id' => 12],
            ['name' => 'Porbandar', 'state_id' => 12],
            ['name' => 'Rajkot', 'state_id' => 12],
            ['name' => 'Sabarkantha', 'state_id' => 12],
            ['name' => 'Surat', 'state_id' => 12],
            ['name' => 'Surendra Nagar', 'state_id' => 12],
            ['name' => 'Tapi', 'state_id' => 12],
            ['name' => 'The Dangs', 'state_id' => 12],
            ['name' => 'Vadodara', 'state_id' => 12],
            ['name' => 'Valsad', 'state_id' => 12],
            ['name' => 'Daman', 'state_id' => 9],
            ['name' => 'Diu', 'state_id' => 9],
            ['name' => 'Dadra & Nagar Haveli', 'state_id' => 8],
            ['name' => 'Ahmed Nagar', 'state_id' => 21],
            ['name' => 'Akola', 'state_id' => 21],
            ['name' => 'Amravati', 'state_id' => 21],
            ['name' => 'Aurangabad', 'state_id' => 21],
            ['name' => 'Beed', 'state_id' => 21],
            ['name' => 'Bhandara', 'state_id' => 21],
            ['name' => 'Buldhana', 'state_id' => 21],
            ['name' => 'Chandrapur', 'state_id' => 21],
            ['name' => 'Dhule', 'state_id' => 21],
            ['name' => 'Gadchiroli', 'state_id' => 21],
            ['name' => 'Gondia', 'state_id' => 21],
            ['name' => 'Hingoli', 'state_id' => 21],
            ['name' => 'Jalgaon', 'state_id' => 21],
            ['name' => 'Jalna', 'state_id' => 21],
            ['name' => 'Kolhapur', 'state_id' => 21],
            ['name' => 'Latur', 'state_id' => 21],
            ['name' => 'Mumbai', 'state_id' => 21],
            ['name' => 'Mumbai Suburban', 'state_id' => 21],
            ['name' => 'Nagpur', 'state_id' => 21],
            ['name' => 'Nanded', 'state_id' => 21],
            ['name' => 'Nandurbar', 'state_id' => 21],
            ['name' => 'Nashik', 'state_id' => 21],
            ['name' => 'Osmanabad', 'state_id' => 21],
            ['name' => 'Parbhani', 'state_id' => 21],
            ['name' => 'Pune', 'state_id' => 21],
            ['name' => 'Raigarh (Maharashtra)', 'state_id' => 21],
            ['name' => 'Ratnagiri', 'state_id' => 21],
            ['name' => 'Sangli', 'state_id' => 21],
            ['name' => 'Satara', 'state_id' => 21],
            ['name' => 'Sindhudurg', 'state_id' => 21],
            ['name' => 'Solapur', 'state_id' => 21],
            ['name' => 'Thane', 'state_id' => 21],
            ['name' => 'Wardha', 'state_id' => 21],
            ['name' => 'Washim', 'state_id' => 21],
            ['name' => 'Yavatmal', 'state_id' => 21],
            ['name' => 'Adilabad', 'state_id' => 2],
            ['name' => 'Anantapur', 'state_id' => 2],
            ['name' => 'Chittoor', 'state_id' => 2],
            ['name' => 'East Godavari', 'state_id' => 2],
            ['name' => 'Guntur', 'state_id' => 2],
            ['name' => 'Hyderabad', 'state_id' => 2],
            ['name' => 'Kadapa (Cuddapah)', 'state_id' => 2],
            ['name' => 'Karim Nagar', 'state_id' => 2],
            ['name' => 'Khammam', 'state_id' => 2],
            ['name' => 'Krishna', 'state_id' => 2],
            ['name' => 'Kurnool', 'state_id' => 2],
            ['name' => 'Mahbubnagar', 'state_id' => 2],
            ['name' => 'Medak', 'state_id' => 2],
            ['name' => 'Nalgonda', 'state_id' => 2],
            ['name' => 'Nellore', 'state_id' => 2],
            ['name' => 'Nizamabad', 'state_id' => 2],
            ['name' => 'Prakasam', 'state_id' => 2],
            ['name' => 'Rangareddy', 'state_id' => 2],
            ['name' => 'Srikakulam', 'state_id' => 2],
            ['name' => 'Visakhapatnam', 'state_id' => 2],
            ['name' => 'Vizianagaram', 'state_id' => 2],
            ['name' => 'Warangal', 'state_id' => 2],
            ['name' => 'West Godavari', 'state_id' => 2],
            ['name' => 'Bagalkot', 'state_id' => 17],
            ['name' => 'Bangalore', 'state_id' => 17],
            ['name' => 'Bangalore Rural', 'state_id' => 17],
            ['name' => 'Belgaum', 'state_id' => 17],
            ['name' => 'Bellary', 'state_id' => 17],
            ['name' => 'Bidar', 'state_id' => 17],
            ['name' => 'Bijapur (Karnataka)', 'state_id' => 17],
            ['name' => 'Chamrajnagar', 'state_id' => 17],
            ['name' => 'Chickmagalur', 'state_id' => 17],
            ['name' => 'Chikkaballapur', 'state_id' => 17],
            ['name' => 'Chitradurga', 'state_id' => 17],
            ['name' => 'Dakshina Kannada', 'state_id' => 17],
            ['name' => 'Davanagere', 'state_id' => 17],
            ['name' => 'Dharwad', 'state_id' => 17],
            ['name' => 'Gadag', 'state_id' => 17],
            ['name' => 'Gulbarga', 'state_id' => 17],
            ['name' => 'Hassan', 'state_id' => 17],
            ['name' => 'Haveri', 'state_id' => 17],
            ['name' => 'Kodagu', 'state_id' => 17],
            ['name' => 'Kolar', 'state_id' => 17],
            ['name' => 'Koppal', 'state_id' => 17],
            ['name' => 'Mandya', 'state_id' => 17],
            ['name' => 'Mysore', 'state_id' => 17],
            ['name' => 'Raichur', 'state_id' => 17],
            ['name' => 'Ramanagara', 'state_id' => 17],
            ['name' => 'Shimoga', 'state_id' => 17],
            ['name' => 'Tumkur', 'state_id' => 17],
            ['name' => 'Udupi', 'state_id' => 17],
            ['name' => 'Uttara Kannada', 'state_id' => 17],
            ['name' => 'Yadgir', 'state_id' => 17],
            ['name' => 'North Goa', 'state_id' => 11],
            ['name' => 'South Goa', 'state_id' => 11],
            ['name' => 'Lakshadweep', 'state_id' => 19],
            ['name' => 'Alappuzha', 'state_id' => 18],
            ['name' => 'Ernakulam', 'state_id' => 18],
            ['name' => 'Idukki', 'state_id' => 18],
            ['name' => 'Kannur', 'state_id' => 18],
            ['name' => 'Kasaragod', 'state_id' => 18],
            ['name' => 'Kollam', 'state_id' => 18],
            ['name' => 'Kottayam', 'state_id' => 18],
            ['name' => 'Kozhikode', 'state_id' => 18],
            ['name' => 'Malappuram', 'state_id' => 18],
            ['name' => 'Palakkad', 'state_id' => 18],
            ['name' => 'Pathanamthitta', 'state_id' => 18],
            ['name' => 'Thiruvananthapuram', 'state_id' => 18],
            ['name' => 'Thrissur', 'state_id' => 18],
            ['name' => 'Wayanad', 'state_id' => 18],
            ['name' => 'Ariyalur', 'state_id' => 31],
            ['name' => 'Chennai', 'state_id' => 31],
            ['name' => 'Coimbatore', 'state_id' => 31],
            ['name' => 'Cuddalore', 'state_id' => 31],
            ['name' => 'Dharmapuri', 'state_id' => 31],
            ['name' => 'Dindigul', 'state_id' => 31],
            ['name' => 'Erode', 'state_id' => 31],
            ['name' => 'Kanchipuram', 'state_id' => 31],
            ['name' => 'Kanyakumari', 'state_id' => 31],
            ['name' => 'Karur', 'state_id' => 31],
            ['name' => 'Krishnagiri', 'state_id' => 31],
            ['name' => 'Madurai', 'state_id' => 31],
            ['name' => 'Nagapattinam', 'state_id' => 31],
            ['name' => 'Namakkal', 'state_id' => 31],
            ['name' => 'Nilgiris', 'state_id' => 31],
            ['name' => 'Perambalur', 'state_id' => 31],
            ['name' => 'Pudukkottai', 'state_id' => 31],
            ['name' => 'Ramanathapuram', 'state_id' => 31],
            ['name' => 'Salem', 'state_id' => 31],
            ['name' => 'Sivaganga', 'state_id' => 31],
            ['name' => 'Thanjavur', 'state_id' => 31],
            ['name' => 'Theni', 'state_id' => 31],
            ['name' => 'Thoothukudi (Tuticorin)', 'state_id' => 31],
            ['name' => 'Tiruchirappalli', 'state_id' => 31],
            ['name' => 'Tirunelveli', 'state_id' => 31],
            ['name' => 'Tiruppur', 'state_id' => 31],
            ['name' => 'Tiruvallur', 'state_id' => 31],
            ['name' => 'Tiruvannamalai', 'state_id' => 31],
            ['name' => 'Tiruvarur', 'state_id' => 31],
            ['name' => 'Vellore', 'state_id' => 31],
            ['name' => 'Viluppuram', 'state_id' => 31],
            ['name' => 'Virudhunagar', 'state_id' => 31],
            ['name' => 'Karaikal', 'state_id' => 27],
            ['name' => 'Mahe', 'state_id' => 27],
            ['name' => 'Puducherry (Pondicherry)', 'state_id' => 27],
            ['name' => 'Yanam', 'state_id' => 27],
            ['name' => 'Nicobar', 'state_id' => 1],
            ['name' => 'North And Middle Andaman', 'state_id' => 1],
            ['name' => 'South Andaman', 'state_id' => 1],
            ['name' => 'Sri Potti Sriramulu Nellore', 'state_id' => 2],
            ['name' => 'YSR', 'state_id' => 2],
            ['name' => 'Kamle', 'state_id' => 3],
            ['name' => 'Kra Daadi', 'state_id' => 3],
            ['name' => 'Longding', 'state_id' => 3],
            ['name' => 'Lepa-Rada', 'state_id' => 3],
            ['name' => 'Lower Siang', 'state_id' => 3],
            ['name' => 'Namsai', 'state_id' => 3],
            ['name' => 'Pakke-Kessang', 'state_id' => 3],
            ['name' => 'Central Siang', 'state_id' => 3],
            ['name' => 'Shi-Yomi', 'state_id' => 3],
            ['name' => 'Biswanath', 'state_id' => 4],
            ['name' => 'Charaideo', 'state_id' => 4],
            ['name' => 'Hojai', 'state_id' => 4],
            ['name' => 'East Karbi Anglong', 'state_id' => 4],
            ['name' => 'Majuli', 'state_id' => 4],
            ['name' => 'South Salmara-Mankachar', 'state_id' => 4],
            ['name' => 'West Karbi Anglong', 'state_id' => 4],
            ['name' => 'Balod', 'state_id' => 7],
            ['name' => 'Baloda Bazar', 'state_id' => 7],
            ['name' => 'Bemetara', 'state_id' => 7],
            ['name' => 'Gariaband', 'state_id' => 7],
            ['name' => 'Kondagaon', 'state_id' => 7],
            ['name' => 'Korea', 'state_id' => 7],
            ['name' => 'Mungeli', 'state_id' => 7],
            ['name' => 'Surajpur', 'state_id' => 7],
            ['name' => 'Sukma', 'state_id' => 7],
            ['name' => 'Aravallis', 'state_id' => 12],
            ['name' => 'Botad', 'state_id' => 12],
            ['name' => 'Chhota Udepur', 'state_id' => 12],
            ['name' => 'Debhoomi Dwarka', 'state_id' => 12],
            ['name' => 'Gandhinagar', 'state_id' => 12],
            ['name' => 'Gir Somnath', 'state_id' => 12],
            ['name' => 'Kutch', 'state_id' => 12],
            ['name' => 'Mehsana', 'state_id' => 12],
            ['name' => 'Morbi', 'state_id' => 12],
            ['name' => 'Mahisagar', 'state_id' => 12],
            ['name' => 'Surendranagar', 'state_id' => 12],
            ['name' => 'Charkhi Dadri', 'state_id' => 13],
            ['name' => 'Gurugram', 'state_id' => 13],
            ['name' => 'Nuh', 'state_id' => 13],
            ['name' => 'Yamunanagar', 'state_id' => 13],
            ['name' => 'Lahaul and Spiti', 'state_id' => 14],
            ['name' => 'Purbi Singhbhum', 'state_id' => 16],
            ['name' => 'Kodarma', 'state_id' => 16],
            ['name' => 'Saraikela Kharsawan', 'state_id' => 16],
            ['name' => 'Pashchimi singhbhum', 'state_id' => 16],
            ['name' => 'Belagavi', 'state_id' => 17],
            ['name' => 'Vijayapura', 'state_id' => 17],
            ['name' => 'Ballari', 'state_id' => 17],
            ['name' => 'Bengaluru Urban', 'state_id' => 17],
            ['name' => 'Bengaluru Rural', 'state_id' => 17],
            ['name' => 'Chamarajnagar', 'state_id' => 17],
            ['name' => 'Chikkamagaluru', 'state_id' => 17],
            ['name' => 'Kalaburagi', 'state_id' => 17],
            ['name' => 'Mysuru', 'state_id' => 17],
            ['name' => 'Tumakuru', 'state_id' => 17],
            ['name' => 'Vijayanagara', 'state_id' => 17],
            ['name' => 'Agar Malwa', 'state_id' => 20],
            ['name' => 'Niwari', 'state_id' => 20],
            ['name' => 'Ahmednagar', 'state_id' => 21],
            ['name' => 'Mumbai City', 'state_id' => 21],
            ['name' => 'Palghar', 'state_id' => 21],
            ['name' => 'Raigad', 'state_id' => 21],
            ['name' => 'Kakching', 'state_id' => 22],
            ['name' => 'Kamjong', 'state_id' => 22],
            ['name' => 'Kangpokpi', 'state_id' => 22],
            ['name' => 'Noney', 'state_id' => 22],
            ['name' => 'Pherzawl', 'state_id' => 22],
            ['name' => 'Tengnoupal', 'state_id' => 22],
            ['name' => 'North Garo Hills', 'state_id' => 23],
            ['name' => 'Ribhoi', 'state_id' => 23],
            ['name' => 'South West Garo Hills', 'state_id' => 23],
            ['name' => 'South West Khasi Hills', 'state_id' => 23],
            ['name' => 'West Jaintia Hills', 'state_id' => 23],
            ['name' => 'Noklak', 'state_id' => 25],
            ['name' => 'Boudh (Bauda)', 'state_id' => 26],
            ['name' => 'Bargarh (Baragarh)', 'state_id' => 26],
            ['name' => 'Balasore', 'state_id' => 26],
            ['name' => 'Debagarh (Deogarh)', 'state_id' => 26],
            ['name' => 'Jajpur', 'state_id' => 26],
            ['name' => 'Jagatsinghpur', 'state_id' => 26],
            ['name' => 'Nabarangpur', 'state_id' => 26],
            ['name' => 'Subarnapur (Sonepur)', 'state_id' => 26],
            ['name' => 'Sundargarh', 'state_id' => 26],
            ['name' => 'Fazilka', 'state_id' => 28],
            ['name' => 'Pathankot', 'state_id' => 28],
            ['name' => 'Chengalpattu', 'state_id' => 31],
            ['name' => 'Kancheepuram', 'state_id' => 31],
            ['name' => 'Kanniyakumari', 'state_id' => 31],
            ['name' => 'Kallakurichi', 'state_id' => 31],
            ['name' => 'The Nilgiris', 'state_id' => 31],
            ['name' => 'Ranipet', 'state_id' => 31],
            ['name' => 'Thoothukkudi', 'state_id' => 31],
            ['name' => 'Tenkasi', 'state_id' => 31],
            ['name' => 'Thiruvallur', 'state_id' => 31],
            ['name' => 'Tirupathur', 'state_id' => 31],
            ['name' => 'Thiruvarur', 'state_id' => 31],
            ['name' => 'Bhadrari Kothagudem', 'state_id' => 36],
            ['name' => 'Jangaon', 'state_id' => 36],
            ['name' => 'Jaya Shankar Bhalupally', 'state_id' => 36],
            ['name' => 'Jagtial', 'state_id' => 36],
            ['name' => 'Jogulamba', 'state_id' => 36],
            ['name' => 'Karimnagar', 'state_id' => 36],
            ['name' => 'Komaram Bheem Asifabad', 'state_id' => 36],
            ['name' => 'Kamareddy', 'state_id' => 36],
            ['name' => 'Mahabubabad', 'state_id' => 36],
            ['name' => 'Medchal Malkajgiri', 'state_id' => 36],
            ['name' => 'Mancherial', 'state_id' => 36],
            ['name' => 'Mulugu', 'state_id' => 36],
            ['name' => 'Nizambad', 'state_id' => 36],
            ['name' => 'Nagarkurnool', 'state_id' => 36],
            ['name' => 'Nirmal', 'state_id' => 36],
            ['name' => 'Peddapalle', 'state_id' => 36],
            ['name' => 'Rajanna Sircilla', 'state_id' => 36],
            ['name' => 'Siddipet', 'state_id' => 36],
            ['name' => 'Suryapet', 'state_id' => 36],
            ['name' => 'Sangareddy', 'state_id' => 36],
            ['name' => 'Vikarabad', 'state_id' => 36],
            ['name' => 'Warangal Rural', 'state_id' => 36],
            ['name' => 'Warangal Urban', 'state_id' => 36],
            ['name' => 'Wanaparthy', 'state_id' => 36],
            ['name' => 'Yadadri', 'state_id' => 36],
            ['name' => 'Gomati', 'state_id' => 32],
            ['name' => 'Khowai', 'state_id' => 32],
            ['name' => 'Sepahijala', 'state_id' => 32],
            ['name' => 'Unokoti', 'state_id' => 32],
            ['name' => 'Amethi', 'state_id' => 33],
            ['name' => 'Gautam Buddh Nagar', 'state_id' => 33],
            ['name' => 'Amroha', 'state_id' => 33],
            ['name' => 'Kasganj', 'state_id' => 33],
            ['name' => 'Lakhimpur Kheri', 'state_id' => 33],
            ['name' => 'Hapur', 'state_id' => 33],
            ['name' => 'Raebareli', 'state_id' => 33],
            ['name' => 'Shamli', 'state_id' => 33],
            ['name' => 'Sambhal', 'state_id' => 33],
            ['name' => 'Shravasti', 'state_id' => 33],
            ['name' => 'Varansi', 'state_id' => 33],
            ['name' => 'Alipurduar', 'state_id' => 35],
            ['name' => 'Purba Bardhaman', 'state_id' => 35],
            ['name' => 'Darjeeling', 'state_id' => 35],
            ['name' => 'Jhargam', 'state_id' => 35],
            ['name' => 'Kalimpong', 'state_id' => 35],
            ['name' => 'Paschim Bardhaman', 'state_id' => 35],
            ['name' => 'North Twenty Four Parganas', 'state_id' => 35],
            ['name' => 'South Twenty Four Parganas', 'state_id' => 35],
            ['name' => 'Purulia', 'state_id' => 35],
            ['name' => 'South East Delhi', 'state_id' => 10],
            ['name' => 'Shahdara', 'state_id' => 10],
            ['name' => 'Badgam', 'state_id' => 15],
            ['name' => 'Punch', 'state_id' => 15],
            ['name' => 'Shupiyan', 'state_id' => 15],
            ['name' => 'Narayanpet', 'state_id' => 36],
        ];

        if ($districts) {
            foreach ($districts as $district) {
                MasterDistrict::updateOrCreate(['name' => $district['name']], $district);
            }
        }
    }
}
